.DEFAULT_GOAL := help

.PHONY: help clean test test.unit test.integration lint lint.fix format typecheck quality \
	dev.up dev.up.http dev.up.grpc dev.down dev.clean dev.restart dev.logs dev.build dev.ps \
	dev.shell dev.migrate dev.migrate.new dev.seed dev.setup dev.test dev.lint dev.generate \
	dev.proto dev.health

# Colors
CYAN := \033[36m
GREEN := \033[32m
RED := \033[31m
RESET := \033[0m

# Docker
DC := docker compose
SVC := fraud-inbound-http

help: ## display this help message
	@echo "$(CYAN)core-fraud-detection — Available Commands$(RESET)"
	@echo ""
	@awk -F ':.*?## ' '/^[a-zA-Z]/ && NF==2 {printf "  $(GREEN)%-25s$(RESET) %s\n", $$1, $$2}' $(MAKEFILE_LIST) | sort

# ==================== LOCAL ====================

clean: ## delete generated byte code and cache files
	find . -name '*.pyc' -delete
	find . -name '__pycache__' -type d -exec rm -rf {} + 2>/dev/null || true
	rm -rf .pytest_cache .mypy_cache .ruff_cache htmlcov .coverage

test: clean ## run all tests with coverage
	pytest tests/ -v --cov=app --cov-report=term-missing

test.unit: ## run unit tests only
	pytest tests/unit/ -v

test.integration: ## run integration tests only
	pytest tests/integration/ -v

lint: ## run linter (ruff check)
	ruff check app/

lint.fix: ## fix linting issues
	ruff check app/ --fix

format: ## format code (ruff format)
	ruff format app/

typecheck: ## run type checker (mypy)
	mypy app/

quality: lint typecheck ## run lint + typecheck
	@echo "$(GREEN)Quality checks passed!$(RESET)"

# ==================== DOCKER — DEVELOPMENT ====================

dev.up: ## start all containers
	$(DC) up -d

dev.up.http: ## start only HTTP API service
	$(DC) up -d $(SVC)

dev.up.grpc: ## start only gRPC service
	$(DC) up -d fraud-inbound-grpc

dev.down: ## stop all containers
	$(DC) down

dev.clean: ## stop containers and remove volumes
	$(DC) down -v

dev.restart: ## restart all containers
	$(DC) restart

dev.logs: ## tail container logs
	$(DC) logs -f

dev.build: ## rebuild Docker images
	$(DC) build

dev.ps: ## show container status
	$(DC) ps

# ==================== DOCKER — DATABASE ====================

dev.migrate: ## run database migrations
	@echo "$(CYAN)Running migrations...$(RESET)"
	$(DC) exec -T $(SVC) alembic upgrade head
	@echo "$(GREEN)Migrations complete!$(RESET)"

dev.migrate.new: ## create new migration (usage: make dev.migrate.new MSG="description")
	$(DC) exec $(SVC) alembic revision --autogenerate -m "$(MSG)"

dev.seed: ## seed default fraud rules
	@echo "$(CYAN)Seeding fraud rules...$(RESET)"
	$(DC) exec -T $(SVC) python -m scripts.seed_rules
	@echo "$(GREEN)Seeding complete!$(RESET)"

dev.setup: dev.migrate dev.seed ## first-time setup: migrate + seed

# ==================== DOCKER — TESTING & QUALITY ====================

dev.test: ## run all tests inside container
	$(DC) exec -T $(SVC) pytest tests/ -v --cov=app --cov-report=term-missing

dev.lint: ## run linter inside container
	$(DC) exec -T $(SVC) ruff check app/

# ==================== DOCKER — UTILITIES ====================

dev.shell: ## open Python shell in container
	$(DC) exec $(SVC) python

dev.generate: ## generate test transactions (usage: make dev.generate COUNT=20)
	$(DC) exec -T $(SVC) python -m scripts.generate_transactions --count $(or $(COUNT),20)

dev.proto: ## regenerate gRPC stubs from proto definitions
	@echo "$(CYAN)Regenerating gRPC stubs...$(RESET)"
	$(DC) exec -T $(SVC) bash scripts/generate_proto.sh
	@echo "$(GREEN)Stubs generated!$(RESET)"

# ==================== DOCKER — HEALTH ====================

dev.health: ## check service health
	@curl -sf http://localhost:8000/health > /dev/null && echo "$(GREEN)✓ HTTP API$(RESET)" || echo "$(RED)✗ HTTP API$(RESET)"
	@curl -sf http://localhost:8000/ready > /dev/null && echo "$(GREEN)✓ HTTP API Ready$(RESET)" || echo "$(RED)✗ HTTP API Ready$(RESET)"
